# Generated by Django 6.1 on 2026-09-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_otpcode_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(help_text='Fernet-encrypted ciphertext of normalized DL number', max_length=256)),
                ('dl_number_display', models.CharField(help_text='Last 4 characters of DL number in plaintext', max_length=4)),
                ('dl_verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('dl_verification_ref', models.CharField(blank=True, help_text='Provider-issued reference ID for async lookup', max_length=100, null=True)),
                ('dl_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dl_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dl_rejection_reason', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'driver verification',
                'verbose_name_plural': 'driver verifications',
                'indexes': [models.Index(fields=['dl_verification_status'], name='idx_dv_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dl_verification_ref__isnull', False)), fields=('dl_verification_ref',), name='uq_dl_verification_ref')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_role', models.CharField(blank=True, choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not Started'), ('role_selected', 'Role Selected'), ('awaiting_dl', 'Awaiting DL'), ('pending_verification', 'Pending Verification'), ('complete', 'Complete')], default='not_started', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'indexes': [models.Index(fields=['onboarding_status'], name='idx_profile_status')],
            },
        ),
    ]
